harmony/harmony/urls.py
from django.contrib import admin
from django.urls import path, include
from harmony_checker.views import profile
from harmony_checker.forms import AuthFormWithSubmit, PasswordChangeFormWithSubmit, PwdResetFormWithSubmit
from django.contrib.auth.views import LoginView, PasswordChangeView, PasswordResetView

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        'harmony_checker/', 
        include('harmony_checker.urls', namespace='harmony_checker'),
    ),
    path('accounts/login/', LoginView.as_view(authentication_form = AuthFormWithSubmit), name='login'),
    path('accounts/password_change/', PasswordChangeView.as_view(form_class = PasswordChangeFormWithSubmit), name='pwd_change'),
    path('accounts/password_reset/', PasswordResetView.as_view(form_class = PwdResetFormWithSubmit), name='pwd_reset'),
    path('accounts/profile/', profile, name='profile'),
    path('accounts/', include('django.contrib.auth.urls')),
]

harmony/harmony_checker/urls.py
from django.urls import path, include

from . import views

app_name = 'harmony_checker'

urlpatterns = [
    path('', views.index, name='index'),
    path('<uuid:score_id>/checked/', views.checked, name='checked'),
    path('<uuid:score_id>/checked_score/', views.checked_score, name='checked_score'),
    path('<uuid:score_id>/score/', views.score, name='score'),
]

harmony/harmony_checker/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
import uuid

from os.path import basename

from . import voiceleading

# Create your models here.

class MusicalTest(models.Model):
    name = models.CharField(max_length = 50, unique=True)
    func = models.CharField(max_length = 50, unique=True)

    def __str__(self):
        return self.name

class Score(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    score = models.FileField(upload_to='uploads/')
    score_display_name = models.CharField(max_length = 50, default=id)
    musical_tests = models.ManyToManyField(MusicalTest)
    checked_score = models.FileField(upload_to='checked/',null=True)
    checked_score_display_name = models.CharField(max_length = 50, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    upload_date = models.DateTimeField('Date Uploaded', default=timezone.now)

    def __str__(self):
        return self.score_display_name

class Result(models.Model):
    score = models.ForeignKey(Score, on_delete=models.CASCADE)
    musical_test = models.ForeignKey(MusicalTest, on_delete=models.CASCADE)
    passed = models.BooleanField(null=True)
    
    def __str__(self):
        return str.format('{0}: {1}', self.score.score_display_name, self.musical_test.name)

harmony/harmony_checker/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm, PasswordResetForm

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

from .models import Score

class ScoreForm(forms.ModelForm):
    class Meta:
        model = Score
        fields = ['score', 'musical_tests']
    helper = FormHelper()
    helper.add_input(Submit('submit', 'Submit', css_class='btn_primary'))

class AuthFormWithSubmit(AuthenticationForm):
    def __init__(self, request, *args, **kwargs):
        super(AuthFormWithSubmit, self).__init__(*args, **kwargs)
        self.request = request
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Submit', css_class='btn_primary'))

class PasswordChangeFormWithSubmit(PasswordChangeForm):
    def __init__(self, *args, **kwargs):
        super(PasswordChangeFormWithSubmit, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Submit', css_class='btn_primary'))

class PwdResetFormWithSubmit(PasswordResetForm):
    def __init__(self, *args, **kwargs):
        super(PwdResetFormWithSubmit, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Submit', css_class='btn_primary'))

harmony/harmony_checker/views.py
from django.conf import settings
from django.contrib.auth import get_user, views as auth_views
from django.contrib.auth.decorators import login_required
from django.core.files import File
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.utils import timezone

from .forms import ScoreForm
from .models import Score, Result
from . import voiceleading

from music21 import converter
import os.path

# Create your views here.

def index(request):
    user = get_user(request)
    if request.method == 'POST':
        score_form = ScoreForm(request.POST, request.FILES)
        new_score = score_form.save()
        if user.is_authenticated:
            new_score.user = user
        new_score.score_display_name = os.path.basename(new_score.score.name)
        new_score.save()
        fname = str.format('{0}/{1}', settings.MEDIA_ROOT, new_score.score.url)
        stream = converter.parse(fname)
        end_height = 1
        for musical_test in new_score.musical_tests.all():
            musical_test_failures = getattr(voiceleading, musical_test.func)(
                stream,
                chordified_stream=stream.chordify(),
            )
            r = Result(score=new_score,musical_test=musical_test)
            r.passed = (len(musical_test_failures) == 0)
            r.save()
            stream, end_height = voiceleading.annotate_stream(musical_test_failures, stream, end_height)
            output_path = os.path.join("{}_checked.xml".format(fname[:-4]))
            stream.write(
                "musicxml", output_path
            )
            with open(output_path) as fp:
                contents = File(fp)
                new_score.checked_score.save(output_path, contents)
            new_score.checked_score_display_name = f"{new_score.score_display_name[:-4]}_checked.xml"
            new_score.save()
        return HttpResponseRedirect(
            reverse('harmony_checker:checked', args=(new_score.id,))
        )
    else:
        score_form = ScoreForm()

    return render(
        request, 
        'harmony_checker/index.html', 
        {'score_form': score_form, 'user': user, 'title': "Check Harmony"}
    )

def checked(request, score_id):
    user = get_user(request)
    score = get_object_or_404(Score, pk=score_id)
    results = Result.objects.filter(score=score_id)

    #generate checked score display name
    return render(
        request, 
        'harmony_checker/checked.html',
        {
            'score': score, 
            'results': results, 
            'user': user,
            'title': 'Results'
        }
    )


def checked_score(request, score_id):
    score = get_object_or_404(Score, pk=score_id)
    response = HttpResponse(score.checked_score, content_type='application/xml')
    response['Content-Disposition'] = f"attachment; filename={score.checked_score_display_name}"
    return response


def score(request, score_id):
    score = get_object_or_404(Score, pk=score_id)
    response = HttpResponse(score.score, content_type='application/xml')
    response['Content-Disposition'] = f"attachment; filename={score.score_display_name}"
    return response

@login_required
def profile(request):
    user = get_user(request)
    scores = Score.objects.filter(user=user).order_by('-upload_date')
    return render(
        request,
        'harmony_checker/profile.html',
        {
            'user': user, 
            'scores': scores,
            'title': "User Profile"
        }
    )

harmony/harmony_checker/templates/harmony_checker/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title> {{title}} </title>
</head>

<body>
    <!--Nav-->
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link" href={% url 'harmony_checker:index' %}>Harmony Checker</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href={% url 'profile' %}>Account</a>
        </li>
        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href={% url 'logout' %}>Log Out</a>
            </li>
        {% endif %}
    </ul>

    <main role="main" class="container">
        <div class="starter-template">
            <h1> {{ title }} </h1>
            {% block content %}
            {% endblock %}
        </div>
    </main>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
</body>

</html>

harmony/harmony_checker/templates/harmony_checker/checked.html
{% extends 'harmony_checker/base.html' %}
{% block content %}
{% if score %}
    <p>Uploaded Score: <a class="btn-link"
            href={% url "harmony_checker:score" score.id %}>{{ score.score_display_name }}</a> </p>
    <p>Checked Score: <a class="btn-link"
            href={% url "harmony_checker:checked_score" score.id %}>{{ score.checked_score_display_name }}</a> </p>

    {% if results %}
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Test</th>
                    <th scope="col">Result</th>
                </tr>
            </thead>
            <tbody>
                {% for result in results.all %}
                <tr>
                    <td>{{ result.musical_test.name }}</td>
                    <td>{% if result.passed %} <span class="badge badge-success">Passed</span>
                        {% else %} <span class="badge badge-danger">Failed</span></td>
                    {% endif %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% endif %}
    {% else %}
    <p>No tests selected.</p>
{% endif %}
{% endblock %}

harmony/harmony_checker/templates/harmony_checker/index.html
{% extends 'harmony_checker/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
{% crispy score_form %}
{% endblock %}

harmony/harmony_checker/templates/harmony_checker/profile.html
{% extends 'harmony_checker/base.html' %}
{% block content %}
<a href={% url "pwd_change" %}>Change Password</a>
{% if scores %}
<table class="table">
    <thead>
        <tr>
            <th scope="col">Score</th>
            <th scope="col">Upload Date</th>
        </tr>
    </thead>
    <tbody>
        {% for score in scores.all %}
        <tr>
            <td><a href={% url "harmony_checker:checked" score.id %}>
                    {{ score.score_display_name }}
                </a></td>
            <td>{{score.upload_date}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p>No scores uploaded.</p>
{% endif %}
{% endblock %}